/** A Trello-style task board, persisted per project in localStorage. */

/** A reference from a task back to the exact spec version it was generated from. */
export interface SpecRef {
  specId: string;
  specTitle: string;
  version: number;
}

/** Independent lifecycle of the agent working a ticket (distinct from the
 *  board column / status the human sets). */
export type AgentStatus = "queued" | "working" | "waiting" | "review" | "done" | "blocked" | "error";

/** A single entry in a ticket's comment thread. The agent posts its progress
 *  here; the human replies to give input. */
export interface Comment {
  id: string;
  author: "agent" | "user" | "system";
  text: string;
  at: number;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  /** Set when the task was generated by AI from a spec version. */
  spec?: SpecRef;
  /** Set when the ticket has been assigned to an agent. */
  assignee?: "agent";
  /** The agent's independent working status (only meaningful when assigned). */
  agentStatus?: AgentStatus;
  comments?: Comment[];
  /** Ids of tasks that must be complete before this one runs. */
  dependsOn?: string[];
}

export interface Column {
  id: string;
  name: string;
  tasks: Task[];
}

/** An immutable snapshot of a spec's content. Versions are append-only. */
export interface SpecVersion {
  version: number;
  content: string;
  createdAt: number;
}

/** A spec (markdown document). Its content is immutable: edits create a new
 *  version rather than mutating an existing one. */
export interface Spec {
  id: string;
  title: string;
  versions: SpecVersion[];
}

export interface Board {
  id: string;
  name: string;
  columns: Column[];
  specs: Spec[];
}

const KEY = (root: string) => `taskboards:${root}`;
const SEL_KEY = (root: string) => `taskboards.selected:${root}`;

export function newId(): string {
  return `tb_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;
}

/** A fresh board with the default Backlog / In Progress / Done columns. */
export function newBoard(name = "Board"): Board {
  return {
    id: newId(),
    name,
    columns: [
      { id: newId(), name: "Backlog", tasks: [] },
      { id: newId(), name: "In Progress", tasks: [] },
      { id: newId(), name: "Done", tasks: [] },
    ],
    specs: [],
  };
}

/** A fresh spec seeded with a first version. */
export function newSpec(title = "Untitled spec"): Spec {
  return {
    id: newId(),
    title,
    versions: [{ version: 1, content: `# ${title}\n\n`, createdAt: Date.now() }],
  };
}

export function latestVersion(spec: Spec): SpecVersion {
  return spec.versions[spec.versions.length - 1];
}

/** Display label + accent colour for an agent status. */
export function agentStatusMeta(s: AgentStatus): { label: string; color: string } {
  switch (s) {
    case "queued": return { label: "Queued", color: "#6b7280" };
    case "working": return { label: "Working", color: "#0a66c2" };
    case "waiting": return { label: "Needs input", color: "#c47f00" };
    case "review": return { label: "Needs review", color: "#8250df" };
    case "done": return { label: "Done", color: "#1a7f37" };
    case "blocked": return { label: "Blocked", color: "#c2410c" };
    case "error": return { label: "Error", color: "#c22" };
  }
}

/** Ensure a loaded board has every field the current model expects. */
function migrateBoard(b: Board): Board {
  return { ...b, specs: Array.isArray(b.specs) ? b.specs : [] };
}

export function loadBoards(root: string): Board[] {
  try {
    const raw = localStorage.getItem(KEY(root));
    const list = raw ? JSON.parse(raw) : [];
    if (Array.isArray(list) && list.length) return list.map(migrateBoard);
  } catch {
    /* ignore */
  }
  return [newBoard()];
}

export function saveBoards(root: string, boards: Board[]) {
  try {
    localStorage.setItem(KEY(root), JSON.stringify(boards));
  } catch {
    /* ignore */
  }
}

export function loadSelectedBoardId(root: string): string | null {
  try {
    return localStorage.getItem(SEL_KEY(root));
  } catch {
    return null;
  }
}

export function saveSelectedBoardId(root: string, id: string) {
  try {
    localStorage.setItem(SEL_KEY(root), id);
  } catch {
    /* ignore */
  }
}
